services:
  api-gateway:
    container_name: "api-gateway"
    hostname: "api-gateway"
    build: .ls 
    ports:
      - "8080:8080"
    expose:
      - "8080" 
    environment:
      - SPRING_PROFILES_ACTIVE=docker